### ISSUE TITLE
bash: golongfuncs: command not found

### ISSUE THREAD

**Issue by Randylcy** [tkrajina/golongfuncs#3]
I have installed the module in the go project successfully. but when I run `golongfuncs` in the CLI, it turns out `bash: golongfuncs: command not found`.

**Comment by Randylcy** [comment]
does anyone know how to fix it?

**Comment by tkrajina** [comment]
https://github.com/tkrajina/golongfuncs/pull/5 should fix this.

**Comment by Randylcy** [comment]
您的邮件我已收到。我尽快查看并回复
