### ISSUE TITLE
All `go install` instruction to README.md

### ISSUE THREAD

**Issue by gogingersnap777** [tkrajina/golongfuncs#4]
### Proposal

It wasn't obvious at first how to install `golongfuncs`. I learned that the correct command is:

```bash
go install  github.com/tkrajina/golongfuncs/...
```

The current command isn't for installation, but to add to the `go.mod` and `go.sum`, along with any dependencies.

A PR is attached with suggested changes.

**Comment by zachajon-cisco** [comment]
PR with change - https://github.com/tkrajina/golongfuncs/pull/5

**Comment by gogingersnap777** [comment]
PR with change - https://github.com/tkrajina/golongfuncs/pull/5

**Comment by gogingersnap777** [comment]
@tkrajina Looking for review/feedback!
