### ISSUE TITLE
Question: Are you open to contributions

### ISSUE THREAD

**Issue by gogingersnap777** [tkrajina/golongfuncs#6]
I'm looking to use your tool to help show the health of some different code bases.

From my perspective, I see some changes that will help with the maintainability of this repo!

Are you open to contributions?

Also, is this project only specific to Go, or were you thinking of extending to other languages? Like Python for example

**Comment by tkrajina** [comment]
Yes, I'm open to contributions, but I can't guarantee I'll reply in a timely manner. Sometimes I just don't have the time to keep up with my open source projects :(

And, yes, this project is specific to go and I don't plan to extend it with other languages.
